/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package log;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author lv1823
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    private static final String ARCHIVO_USUARIOS = "usuarios.txt";
    
    public Registrar() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AtrasBtn = new javax.swing.JLabel();
        XBtn = new javax.swing.JLabel();
        OKBtn = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPsswrd = new javax.swing.JPasswordField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AtrasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AtrasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtrasBtnMouseClicked(evt);
            }
        });
        getContentPane().add(AtrasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 80));

        XBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XBtnMouseClicked(evt);
            }
        });
        getContentPane().add(XBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 90, 60));

        OKBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKBtnMouseClicked(evt);
            }
        });
        getContentPane().add(OKBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 630, 100, 70));

        txtNombre.setBackground(new java.awt.Color(153, 153, 153));
        txtNombre.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 2));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 560, 60));

        txtPsswrd.setBackground(new java.awt.Color(153, 153, 153));
        txtPsswrd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPsswrd.setForeground(new java.awt.Color(255, 255, 255));
        txtPsswrd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 2));
        getContentPane().add(txtPsswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 560, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/M/REGISTRO.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKBtnMouseClicked
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(ARCHIVO_USUARIOS, true))) {
            bw.write(txtNombre.getText() + "," + new String(txtPsswrd.getPassword()));
            bw.newLine();
            this.dispose();
        } catch (IOException e) {
            System.err.println("Error al escribir en el archivo de usuarios: " + e.getMessage());
        }
    }//GEN-LAST:event_OKBtnMouseClicked

    private void XBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBtnMouseClicked
this.dispose();
    }//GEN-LAST:event_XBtnMouseClicked

    private void AtrasBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasBtnMouseClicked
       this.dispose();
    }//GEN-LAST:event_AtrasBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AtrasBtn;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel OKBtn;
    private javax.swing.JLabel XBtn;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPsswrd;
    // End of variables declaration//GEN-END:variables
}
